name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
      - run: npm install

      - uses: mansagroup/nrwl-nx-action@v3
        with:
          targets: lint,test,build
          all: 'true'
